import React from "react";
import { motion } from "motion/react";
import { 
  Sparkles, 
  FileText, 
  CheckCircle, 
  ArrowRight, 
  Shield, 
  Zap, 
  Layers, 
  Cloud, 
  ChevronRight, 
  HelpCircle,
  TrendingUp,
  Download,
  Lock,
  Star
} from "lucide-react";

interface LandingPageProps {
  onStartTesting: () => void;
  onOpenAuth: (mode: "signin" | "signup") => void;
}

export default function LandingPage({ onStartTesting, onOpenAuth }: LandingPageProps) {
  // Mock demonstration score state that counts up
  const [demoScore, setDemoScore] = React.useState(42);

  React.useEffect(() => {
    const timer = setTimeout(() => {
      if (demoScore < 94) {
        setDemoScore((prev) => prev + 1);
      }
    }, 45);
    return () => clearTimeout(timer);
  }, [demoScore]);

  const features = [
    {
      icon: <Sparkles className="w-5 h-5 text-emerald-600" />,
      title: "Contextual AI Tailoring",
      desc: "Our advanced parser analyzes any target job description and naturally weaves essential key phrases into your experiences."
    },
    {
      icon: <TrendingUp className="w-5 h-5 text-emerald-600" />,
      title: "Live ATS Scoring",
      desc: "Instant feedback loops show you exactly which high-yield keywords are present and which ones are missing for maximum compliance."
    },
    {
      icon: <Layers className="w-5 h-5 text-emerald-600" />,
      title: "Multiple Layout Styles",
      desc: "Toggle seamlessly between Classic, Modern, Tech, and Creative layouts, formatted strictly according to corporate HR rules."
    },
    {
      icon: <Cloud className="w-5 h-5 text-emerald-600" />,
      title: "Autosave Cloud Sync",
      desc: "Every keystroke and AI tailoring is backed up instantly. Access your resume securely from any device, anytime."
    }
  ];

  const plans = [
    {
      name: "Free Plan",
      price: "$0",
      period: "forever",
      cvLimit: "5 CVs tailored",
      desc: "Perfect for testing our system and getting a fast baseline.",
      features: [
        "Interactive profile builder",
        "Direct plain text resume imports",
        "Live ATS keyword tracking & matching",
        "Classic & Modern templates",
        "Interactive sandbox editor",
        "Up to 5 CV tailored suggestions"
      ],
      cta: "Try Free Sandbox",
      action: onStartTesting,
      popular: false,
      border: "border-slate-200 bg-white"
    },
    {
      name: "Pro Career",
      price: "$12",
      period: "per month",
      cvLimit: "30 CVs tailored",
      desc: "For serious job seekers applying to high-yield target roles.",
      features: [
        "Everything in Free",
        "Up to 30 automated tailors / month",
        "Direct PDF downloads & exports",
        "Premium layout templates (Tech & Creative)",
        "Extended interview tips generated by AI",
        "Direct cloud database sync & backups",
        "Priority AI processing queues"
      ],
      cta: "Register & Upgrade",
      action: () => onOpenAuth("signup"),
      popular: true,
      border: "border-emerald-500 bg-emerald-50/10 ring-2 ring-emerald-500/10"
    },
    {
      name: "Unlimited VIP",
      price: "$29",
      period: "per month",
      cvLimit: "100 CVs tailored",
      desc: "For professional agencies, consultants, and power users.",
      features: [
        "Everything in Pro",
        "Up to 100 automated tailors / month",
        "Multi-profile cloud management",
        "Advanced deep research resume auditing",
        "Beta access to Cover Letter Matcher",
        "Immediate VIP dedicated developer support"
      ],
      cta: "Get Unlimited Access",
      action: () => onOpenAuth("signup"),
      popular: false,
      border: "border-slate-200 bg-white"
    }
  ];

  return (
    <div className="bg-[#f8fafc] text-slate-900 font-sans min-h-screen">
      {/* Navigation Rail */}
      <nav className="sticky top-0 z-40 bg-white/80 backdrop-blur-md border-b border-gray-100 px-4 md:px-8 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="bg-emerald-600 text-white p-2 rounded-xl shadow-md shadow-emerald-600/10">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <span className="text-[10px] font-black text-emerald-600 uppercase tracking-widest block">AI-Driven Workflows</span>
              <h1 className="text-md font-bold text-gray-900 tracking-tight">AI CV Builder</h1>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button 
              onClick={onStartTesting}
              className="text-xs font-bold text-gray-600 hover:text-gray-900 px-3 py-1.5 transition cursor-pointer"
            >
              Test for Free
            </button>
            <button 
              onClick={() => onOpenAuth("signin")}
              className="text-xs font-bold text-gray-700 bg-gray-100 hover:bg-gray-200 px-4 py-2 rounded-xl transition cursor-pointer"
              id="landing-signin-btn"
            >
              Sign In
            </button>
            <button 
              onClick={() => onOpenAuth("signup")}
              className="text-xs font-bold text-white bg-emerald-600 hover:bg-emerald-500 px-4 py-2 rounded-xl shadow-xs transition cursor-pointer"
              id="landing-register-btn"
            >
              Register
            </button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative overflow-hidden py-16 md:py-24 border-b border-slate-100 bg-white">
        <div className="max-w-7xl mx-auto px-4 md:px-8 grid lg:grid-cols-12 gap-12 items-center">
          <div className="lg:col-span-7 space-y-6">
            <motion.div
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="inline-flex items-center gap-2 px-3 py-1 bg-emerald-50 text-emerald-700 rounded-full text-xs font-bold"
            >
              <Sparkles className="w-3.5 h-3.5 animate-pulse" />
              <span>Next-Gen ATS Parser V3.5</span>
            </motion.div>

            <motion.h1 
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="text-4xl md:text-5xl font-black text-slate-900 tracking-tight leading-tight"
            >
              Tailor your CV to <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-600 to-teal-500">
                Any Job Description
              </span>{" "}
              instantly.
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="text-slate-500 text-sm md:text-base leading-relaxed max-w-xl"
            >
              Stop sending generic resumes. Our intelligent model isolates crucial skills, optimizes keywords, increases your ATS compliance score, and prepares high-impact interview answers automatically.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.3 }}
              className="flex flex-wrap items-center gap-3 pt-2"
            >
              <button
                onClick={() => onOpenAuth("signup")}
                className="px-6 py-3 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-bold flex items-center gap-2 shadow-md transition cursor-pointer"
                id="hero-get-started"
              >
                <span>Create Free Account & Sync</span>
                <ArrowRight className="w-4 h-4" />
              </button>
              
              <button
                onClick={onStartTesting}
                className="px-6 py-3 border border-slate-200 text-slate-700 hover:bg-slate-50 rounded-xl text-xs font-bold flex items-center gap-1.5 transition cursor-pointer"
                id="hero-test-free"
              >
                <span>Test for Free (No Sign Up)</span>
              </button>
            </motion.div>

            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.5 }}
              className="flex flex-wrap items-center gap-6 text-xs text-slate-400 font-semibold pt-4"
            >
              <div className="flex items-center gap-1.5">
                <CheckCircle className="w-4 h-4 text-emerald-500" />
                <span>Compliant with Workday, Taleo & Greenhouse</span>
              </div>
              <div className="flex items-center gap-1.5">
                <CheckCircle className="w-4 h-4 text-emerald-500" />
                <span>High Quality Direct PDF Download</span>
              </div>
            </motion.div>
          </div>

          {/* Interactive Visual Element */}
          <div className="lg:col-span-5 relative">
            <motion.div 
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.6 }}
              className="bg-slate-900 text-slate-100 rounded-3xl p-6 shadow-2xl relative border border-slate-800 overflow-hidden"
            >
              <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500/10 rounded-full blur-3xl" />
              
              <div className="flex items-center justify-between border-b border-slate-800 pb-4 mb-6">
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 rounded-full bg-red-500" />
                  <div className="w-3 h-3 rounded-full bg-yellow-500" />
                  <div className="w-3 h-3 rounded-full bg-green-500" />
                </div>
                <span className="text-[10px] font-mono text-slate-500">LIVE ATS METRICS</span>
              </div>

              <div className="space-y-4">
                <div className="p-4 bg-slate-800/40 border border-slate-800 rounded-2xl flex items-center justify-between">
                  <div>
                    <h3 className="font-bold text-xs text-white">Original CV Strength</h3>
                    <p className="text-[10px] text-slate-400 mt-0.5">Missing high-yield keywords</p>
                  </div>
                  <span className="text-sm font-black text-rose-400">42%</span>
                </div>

                <div className="flex justify-center my-2">
                  <div className="w-6 h-6 rounded-full bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
                    <Zap className="w-3.5 h-3.5 animate-bounce" />
                  </div>
                </div>

                <div className="p-4 bg-emerald-950/20 border border-emerald-500/20 rounded-2xl flex items-center justify-between relative overflow-hidden">
                  <div className="absolute inset-0 bg-emerald-500/5 animate-pulse" />
                  <div>
                    <h3 className="font-bold text-xs text-emerald-400">AI Tailored Performance</h3>
                    <p className="text-[10px] text-emerald-500/80 mt-0.5">Optimized alignment complete</p>
                  </div>
                  <span className="text-base font-black text-emerald-400">{demoScore}%</span>
                </div>
              </div>

              {/* Progress visual bar */}
              <div className="mt-6 space-y-1.5">
                <div className="flex justify-between text-[10px] font-semibold text-slate-400">
                  <span>ATS Score Target Threshold</span>
                  <span>94% Success</span>
                </div>
                <div className="h-1.5 w-full bg-slate-800 rounded-full overflow-hidden">
                  <motion.div 
                    initial={{ width: "42%" }}
                    animate={{ width: "94%" }}
                    transition={{ duration: 1.5, delay: 0.2 }}
                    className="h-full bg-emerald-500"
                  />
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Feature list */}
      <section className="py-20 max-w-7xl mx-auto px-4 md:px-8">
        <div className="text-center max-w-2xl mx-auto mb-16 space-y-3">
          <span className="text-xs font-bold text-emerald-600 uppercase tracking-widest block">Core Competencies</span>
          <h2 className="text-3xl font-black text-slate-900 tracking-tight">Everything you need to bypass standard HR algorithms</h2>
          <p className="text-sm text-slate-500 leading-relaxed">We focus strictly on structural consistency, semantic mapping, and high-fidelity layouts that get you through real ATS machines.</p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feat, idx) => (
            <div key={idx} className="bg-white border border-slate-100 p-6 rounded-2xl shadow-xs space-y-4">
              <div className="p-3 bg-emerald-50 rounded-xl inline-block">
                {feat.icon}
              </div>
              <h3 className="text-sm font-bold text-slate-900">{feat.title}</h3>
              <p className="text-xs text-slate-500 leading-relaxed">{feat.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Pricing Sections */}
      <section className="py-20 bg-slate-50 border-t border-b border-slate-100">
        <div className="max-w-7xl mx-auto px-4 md:px-8">
          <div className="text-center max-w-2xl mx-auto mb-16 space-y-3">
            <span className="text-xs font-bold text-emerald-600 uppercase tracking-widest block">Flexible Access Plans</span>
            <h2 className="text-3xl font-black text-slate-900 tracking-tight">Upgrade your job search frequency</h2>
            <p className="text-sm text-slate-500 leading-relaxed">Choose a pricing plan that fits your current career hunting scope. Start testing completely for free.</p>
          </div>

          <div className="grid md:grid-cols-3 gap-8 items-stretch">
            {plans.map((plan, idx) => (
              <div 
                key={idx} 
                className={`border rounded-3xl p-6 md:p-8 flex flex-col justify-between transition relative ${plan.border}`}
              >
                {plan.popular && (
                  <span className="absolute -top-3.5 left-1/2 -translate-x-1/2 bg-emerald-600 text-white text-[10px] font-black uppercase tracking-widest px-3.5 py-1 rounded-full shadow-md flex items-center gap-1">
                    <Star className="w-3 h-3 fill-white" />
                    Most Popular
                  </span>
                )}

                <div className="space-y-6">
                  <div>
                    <h3 className="text-md font-bold text-slate-900">{plan.name}</h3>
                    <p className="text-xs text-slate-500 mt-1">{plan.desc}</p>
                  </div>

                  <div className="flex items-baseline gap-1">
                    <span className="text-4xl font-black text-slate-900">{plan.price}</span>
                    <span className="text-xs text-slate-500 font-semibold">/ {plan.period}</span>
                  </div>

                  <div className="px-3.5 py-1.5 bg-slate-100 rounded-xl inline-block text-xs font-bold text-slate-700">
                    {plan.cvLimit}
                  </div>

                  <hr className="border-slate-100" />

                  <ul className="space-y-3 text-xs text-slate-600">
                    {plan.features.map((feat, fIdx) => (
                      <li key={fIdx} className="flex items-start gap-2.5">
                        <CheckCircle className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                        <span>{feat}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="pt-8">
                  <button
                    onClick={plan.action}
                    className={`w-full py-3 px-4 rounded-xl text-xs font-bold text-center transition cursor-pointer ${
                      plan.popular 
                        ? "bg-emerald-600 hover:bg-emerald-500 text-white shadow-md shadow-emerald-600/10" 
                        : "bg-white hover:bg-slate-50 border border-slate-200 text-slate-700"
                    }`}
                  >
                    {plan.cta}
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Test for free promo CTA */}
      <section className="py-20 max-w-5xl mx-auto px-4 md:px-8 text-center">
        <div className="bg-slate-900 text-white rounded-3xl p-8 md:p-12 shadow-xl relative overflow-hidden border border-slate-800">
          <div className="absolute top-0 left-0 w-64 h-64 bg-emerald-500/10 rounded-full blur-3xl" />
          <div className="relative space-y-6 max-w-2xl mx-auto">
            <h2 className="text-2xl md:text-3xl font-black tracking-tight">Want to test the AI system first?</h2>
            <p className="text-xs md:text-sm text-slate-300 leading-relaxed">
              Launch our interactive editor immediately. You can enter details, upload plain text, experience the automatic tailoring engine, and adjust templates completely for free. No registration required.
            </p>
            <div className="pt-2 flex flex-col sm:flex-row justify-center items-center gap-3">
              <button
                onClick={onStartTesting}
                className="w-full sm:w-auto px-6 py-3.5 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl transition shadow-md cursor-pointer flex items-center justify-center gap-2"
                id="sandbox-cta-btn"
              >
                <Zap className="w-4 h-4" />
                <span>Launch Interactive Sandbox</span>
              </button>
              <button
                onClick={() => onOpenAuth("signup")}
                className="w-full sm:w-auto px-6 py-3.5 bg-slate-800 hover:bg-slate-700 text-white text-xs font-bold rounded-xl transition cursor-pointer flex items-center justify-center gap-2"
              >
                <Lock className="w-4 h-4 text-emerald-400" />
                <span>Create Account</span>
              </button>
            </div>
            <p className="text-[10px] text-slate-400 font-medium">
              Note: Direct high-fidelity PDF downloading and permanent cloud syncing require a free registered account.
            </p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-100 py-10 bg-white">
        <div className="max-w-7xl mx-auto px-4 md:px-8 flex flex-col sm:flex-row justify-between items-center gap-4 text-xs text-slate-400 font-semibold">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-lg bg-emerald-600 text-white flex items-center justify-center font-bold text-xs">CV</div>
            <span>© 2026 AI CV Builder & Tailorer. All rights reserved.</span>
          </div>
          <div className="flex items-center gap-6">
            <span className="hover:text-slate-600 cursor-pointer">Terms of Service</span>
            <span className="hover:text-slate-600 cursor-pointer">Privacy Policy</span>
            <span className="hover:text-slate-600 cursor-pointer text-emerald-600 font-extrabold">Active</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
